import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>屠屠的機器人指令空間</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>
					屠屠的機器人指令空間
				</h1>

				<p className={styles.description}>
					這邊是給屠屠的機器人讀取程式碼的空間。
				</p>

				<div className={styles.grid}>
					<a href="https://www.twitch.tv/wj654cj86" className={styles.card}>
						<h2>屠屠圖奇</h2>
						<p>屠屠的圖奇實況連結。</p>
					</a>
					<a href="https://www.youtube.com/c/%E5%B1%A0%E5%BF%97%E8%8F%AF" className={styles.card}>
						<h2>屠屠Youtube</h2>
						<p>屠屠的Youtube連結。</p>
					</a>
					<a href="https://www.facebook.com/wj654cj86/" className={styles.card}>
						<h2>屠屠臉書</h2>
						<p>屠屠的臉書連結。</p>
					</a>
				</div>
			</main>
		</>
	);
}
